# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d6f6b8b1df6521bcd1535ace7d9536ab3bfd5a01a0f683c47ab7bb3ce847e76ff36acd100f71033cb3f4e9224ddf1dfdf68c9ea193bc919bdfaf3e0d825ef1

test:
  secret_key_base: 275a2af8392184e4b34dbfebe786f60a3a40ac1a0a6bf0d175ab402271e4d3a721e9f026c5fc8dc95839a7ac574459683a79bf14298b4ae337c7cab1379833f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
